# Generated by Django 5.2.3 on 2025-06-12 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=70)),
                ('note_body', models.CharField(max_length=210)),
                ('note_tags', models.JSONField(default=list)),
            ],
        ),
    ]
